-- H2 表结构（应用启动时由 spring.sql.init 幂等执行，重复启动无副作用）
-- rank 故意不加引号：H2 会把不加引号的标识符存成大写，和 Hibernate 生成的 SQL 对得上。
CREATE TABLE IF NOT EXISTS novel_rank (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rank VARCHAR(50) NOT NULL,
    book_id VARCHAR(50),
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100),
    description VARCHAR(20000),
    status VARCHAR(20),
    read_count VARCHAR(20),
    read_count_raw BIGINT,
    last_chapter VARCHAR(200),
    update_time VARCHAR(50),
    thumb_uri VARCHAR(500),
    category_name VARCHAR(50),
    word_count VARCHAR(20),
    create_time TIMESTAMP,
    update_time_db TIMESTAMP,
    is_blocked BOOLEAN DEFAULT FALSE NOT NULL,
    blocked_time TIMESTAMP,
    CONSTRAINT uk_novel_rank_book_id UNIQUE (book_id)
);

CREATE INDEX IF NOT EXISTS idx_category ON novel_rank (category_name);

-- 同一本书可同时上多个分类榜（科幻末世/游戏体育/悬疑脑洞男女频共用 category_id），
-- 唯一性从 book_id 全局唯一改为 (category_code, book_id) 组合唯一。
-- 老库升级：先加列（历史行 gender 由 DEFAULT 1 落成男频），再换约束；
-- NULL book_id 行在唯一约束里互不冲突（H2 把 NULL 视为互异）。
ALTER TABLE novel_rank ADD COLUMN IF NOT EXISTS category_code VARCHAR(50);
ALTER TABLE novel_rank ADD COLUMN IF NOT EXISTS gender TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE novel_rank DROP CONSTRAINT IF EXISTS uk_novel_rank_book_id;
ALTER TABLE novel_rank ADD CONSTRAINT IF NOT EXISTS uk_novel_rank_cat_book UNIQUE (category_code, book_id);
CREATE INDEX IF NOT EXISTS idx_category_code ON novel_rank (category_code);

-- 运行时配置（rank_type / display_categories），由 StartupDataInitializer 播种、ConfigService 缓存
CREATE TABLE IF NOT EXISTS app_config (
    cfg_key VARCHAR(100) PRIMARY KEY,
    cfg_value VARCHAR(4000) NOT NULL,
    update_time_db TIMESTAMP
);
